version: '3.8'
services:
  db:
    image: postgres
    container_name: 2brother
    user: root
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
  2brother-admin:
    image: dpage/pgadmin4:latest
    container_name: 2brother-admin
    volumes:
      - 2brother-admin:/var/lib/pgadmin
    ports:
      - '8000:80'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
volumes:
  db:
    driver: local
  2brother-admin:
    driver: local
networks:
  default:
    name: 2brother